### ISSUE TITLE
Check what is Keycloack

### ISSUE THREAD

**Issue by patricksan** [cloud-erp-school-system/backend#5]
Have everyone in the team to try to understand what is https://www.keycloak.org.
Read the documentation and let me know if you have doubts.

**Comment by patricksan** [comment]
@patricksan :white_check_mark:

**Comment by ianaa** [comment]
:white_check_mark:
 
 Will we have users with different permission levels? Does keycloak handle that?

**Comment by patricksan** [comment]
We will have that. Teachers, Students, Schools, and so one.
Keycloack was chosen because of this.

**Comment by ConnectedLearner** [comment]
@ianaa Yes we have various users with their admin portals. Software should come with in-built 9 or 14  users considered as full time staff of a school ( each has admin portal):


USER TYPES

1.Super Admin


2.Admin,


3.Teachers 


4.Students


5.Parents

6.Front Office  /Receptionist

7.Accountant,

 8.Bus Driver, 

9.Medical Record,

10.Hotel ,  

11.Librarian, 

12.A Couk, 

13.Security Guardian, 

 14.Inventory admin.


Other Employees: Select
